"""Abstract base class for all trading strategies.

All strategies must inherit from BaseStrategy and implement the required methods.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any


@dataclass
class TradeSignal:
    """Represents a trading signal generated by a strategy."""

    market_id: str
    token_id: str
    side: str  # "BUY" or "SELL"
    confidence: float  # 0-1
    edge: float  # Probability edge (our estimate - market price)
    suggested_size: float  # Suggested position size in USDC
    price: float  # Market price at time of signal
    reasoning: str  # Human-readable explanation
    strategy_name: str  # Which strategy generated this


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    @abstractmethod
    def evaluate(self, market_data: dict[str, Any]) -> TradeSignal | None:
        """Evaluate a market and optionally generate a trade signal.

        Args:
            market_data: Full market context including prices, news, sentiment.

        Returns:
            A TradeSignal if an opportunity is found, None otherwise.
        """
        ...

    @abstractmethod
    def get_name(self) -> str:
        """Return the strategy name for logging and tracking."""
        ...
