# TODO: Implement in Phase 4
"""Abstract base class for all trading strategies.

All strategies must inherit from BaseStrategy and implement the required methods.
"""

from abc import ABC, abstractmethod
from typing import Any


class TradeSignal:
    """Represents a trading signal generated by a strategy."""

    def __init__(
        self,
        market_id: str,
        side: str,
        confidence: float,
        suggested_size: float,
        reasoning: str,
    ) -> None:
        """Initialize a trade signal.

        Args:
            market_id: The market to trade.
            side: "BUY" or "SELL".
            confidence: Confidence level 0-1.
            suggested_size: Suggested position size.
            reasoning: Human-readable explanation of the signal.
        """
        self.market_id = market_id
        self.side = side
        self.confidence = confidence
        self.suggested_size = suggested_size
        self.reasoning = reasoning


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    @abstractmethod
    def evaluate(self, market_data: dict[str, Any]) -> TradeSignal | None:
        """Evaluate a market and optionally generate a trade signal.

        Args:
            market_data: Full market context including prices, news, sentiment.

        Returns:
            A TradeSignal if an opportunity is found, None otherwise.
        """
        ...

    @abstractmethod
    def get_name(self) -> str:
        """Return the strategy name for logging and tracking."""
        ...
